dist: bionic
language: ruby
rvm: 2.7
before_install:
  - export FAISS_VERSION=1.6.1
  - ./test/ci/install_faiss.sh
cache:
  bundler: true
  directories:
    - $HOME/faiss
before_script: bundle exec rake compile
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
