dist: bionic
language: ruby
rvm: 2.7
addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
before_install:
  - export FAISS_VERSION=1.6.1
  - ./test/ci/install_faiss.sh
  - echo $LD_LIBRARY_PATH
  - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
  - ls /usr/local/lib | grep faiss
cache:
  bundler: true
  directories:
    - $HOME/faiss
before_script: bundle exec rake compile
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
