dist: bionic
language: ruby
rvm: 2.7
addons:
  apt:
    packages:
      - libblas-dev
before_install:
  - export FAISS_VERSION=1.6.1
  - ./test/ci/install_faiss.sh
  - export LD_LIBRARY_PATH=$HOME/faiss/$FAISS_VERSION:$LD_LIBRARY_PATH
cache:
  bundler: true
  directories:
    - $HOME/faiss
before_script: bundle exec rake compile
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
