dist: bionic
language: ruby
rvm: 2.7
addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
cache:
  bundler: true
before_script: bundle exec rake compile
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
