name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 3.3
            os: ubuntu-22.04
          # TODO figure out issue with IndexPQ and Ruby 3.2.3
          - ruby: 3.2.2
            os: ubuntu-22.04
          - ruby: 3.1
            os: ubuntu-20.04
          - ruby: "3.0"
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: sudo apt-get install libblas-dev liblapack-dev
      - if: ${{ startsWith(matrix.os, 'macos') }}
        run: brew install openblas lapack libomp
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: MAKE="make -j$(nproc)" bundle exec rake compile
      - run: bundle exec rake test
